name: "Ruff Lint/Formatting"

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  ruff:
    name: Ruff Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff check
        uses: astral-sh/ruff-action@v3
        with:
          args: "check ."

      - name: Run Ruff format check
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check ."